version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: jenkins-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    # TODO: automatic import of sql file
    volumes:
      - ./mysql-dump:/database

  hive-server:
    image: hive
    container_name: jenkins-hive-server
    restart: always
    ports:
      - "3000:3000"
    external_links:
      - db
  
  

